Repository CMU-313/nodebb-s25-airm, pull requests merged in 2025-02, with the labels that each got.

#20 Implemented search topics api function, attempted to integrate frontend and backend api
  src/api/search.js
  src/plugins/index.js
  test/search-topic-api.js
Labels: backend, frontend

#16 Adding text input for category folders
  custom-theme/.gitignore
  custom-theme/.npmignore
  public/language/en-US/admin/manage/folders.json
  src/views/admin/partials/categories/create.tpl
Labels: frontend

#21 Fixed the merging error resulted from previous merge between main and search
  custom-theme/templates/category.tpl
  src/api/search.js
  src/plugins/index.js
  test/search-topic-api.js
Labels: bug
